version: '3'
services:
   db:
     image: mysql:5.7.22
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: test
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 8080:80
     restart: always

     
